name = "bertie"
author = "berlord"
version = "0.1.0"
description = "A NeoForge 1.21.1 modpack: the S1 progression questline on top of a large exploration/tech/magic mod set."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f198c2ccb883e542c81fd4e81bd737d5ae806f28fb0c23fb9e694b75bbfbff1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
