name = "bertie"
author = "berlord"
version = "0.1.0"
description = "A large, work-in-progress NeoForge 1.21.1 exploration, technology, and magic modpack, currently focused on integrated early-to-mid-game progression."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe5157d89d993a537a43452f84cd5033a01fda42b27bffda58d31acfe223e11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
