name = "bertie"
author = "berlord"
version = "0.1.0"
description = "A NeoForge 1.21.1 modpack: the S1 progression questline on top of a large exploration/tech/magic mod set."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d31d85e7601d6ed01cefd9b3f03a239f7436bbadec7b2148c7c85e23605c3b8b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
