name: Client world join

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: client-world-join-${{ github.ref }}
  cancel-in-progress: true

jobs:
  world-join:
    uses: bertie-mc/bertie-ci/.github/workflows/pack-client.yml@v3.3.2
