name: Server readiness

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: server-readiness-${{ github.ref }}
  cancel-in-progress: true

jobs:
  readiness:
    uses: bertie-mc/bertie-ci/.github/workflows/pack-server.yml@v3.5.0
