name: Validate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: bertie-mc/bertie-ci/.github/workflows/pack-validate.yml@v3.3.3

  resolve:
    uses: bertie-mc/bertie-ci/.github/workflows/pack-resolve.yml@v3.3.3
